FROM python:3.12-bookworm

ARG POETRY_VERSION="1.8.3"

WORKDIR /opt/app

RUN pip install --upgrade pip poetry==${POETRY_VERSION}

RUN apt update && apt install -y \
  ca-certificates \
  curl \
  gnupg

RUN mkdir -p /etc/apt/keyrings \
  && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
  && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_22.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

RUN apt update && apt install -y nodejs && npm install --global yarn
