version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # env_file:
    #   - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    tty: true
  # database:
  #   image: mariadb:10.6
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MARIADB_ROOT_PASSWORD: "p455w0rd"
  #     MARIADB_DATABASE: "app"
  #     MARIADB_USER: "user"
  #     MARIADB_PASSWORD: "password"
